Move persist.adb.tcp.port from Vendor to Product Partition
As per GMS requirements document,for devices launching with
Android 11 or higher, the names of property contexts of vendor
(or odm) properties MUST start with vendor_ or odm_.

Keeping persist.adb.tcp.port in vendor partition and exporting it
to system partition using exported2_system_prop will violate this
requirement and cause VTS failures. Since this property is used
in system partition but is owned by vendor the correct way is
adding it in Product partition.

The below is the VTS error reported for same:

Failing TC:
__main__.VtsTrebleSysPropTest#testVendorPropertyTypes
__main__.VtsTrebleSysPropTest#testVendorPropertyNames

AssertionError: 3 != 0 : properties in
/vendor/etc/selinux/vendor_property_contexts have wrong
property types: name: persist.adb.tcp.port,
type: u:object_r:exported2_system_prop:s0

Tracked-On: OAM-95809
Signed-off-by: svenate <salini.venate@intel.com>
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>